CREATE TABLE `anlage` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `status` varchar(20) DEFAULT 'draft',
  `sort` int(10) unsigned DEFAULT NULL,
  `owner` int(10) unsigned DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `modified_by` int(10) unsigned DEFAULT NULL,
  `modified_on` datetime DEFAULT NULL,
  `beschreibung` text,
  `avanti_link` varchar(200) DEFAULT NULL,
  `anlagenname` varchar(200) NOT NULL,
  `kontaktperson` int(10) DEFAULT NULL,
  `standort` varchar(200) DEFAULT NULL COMMENT 'z.B. BuLavard, viamova',
  `standortcode` varchar(200) DEFAULT NULL COMMENT 'gem. Raster',
  `plannachfuehrung` date DEFAULT NULL,
  `anlagen_id` varchar(200) DEFAULT NULL COMMENT 'siehe https://avanti.bula21.ch/x/2zDJAQ',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `anlagen_id` (`anlagen_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5676 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `projekt` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `status` varchar(20) DEFAULT 'draft',
  `sort` int(10) unsigned DEFAULT NULL,
  `owner` int(10) unsigned DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `modified_by` int(10) unsigned DEFAULT NULL,
  `modified_on` datetime DEFAULT NULL,
  `beginn_nutzung` date DEFAULT NULL,
  `ende_nutzung` date DEFAULT NULL,
  `abnahmeart` int(10) DEFAULT NULL,
  `abnahmedatum` date DEFAULT NULL,
  `anlage` int(10) DEFAULT NULL,
  `projektname` varchar(200) DEFAULT NULL,
  `auftraggeber` int(10) DEFAULT NULL,
  `verantwortliche_person_betrieb` int(10) DEFAULT NULL,
  `ressort_betrieb` int(10) DEFAULT NULL,
  `beschreibung` text,
  `beginn_nutzung_zeit` time DEFAULT NULL,
  `ende_nutzung_zeit` time DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2639 DEFAULT CHARSET=utf8mb4;
